name: reqs_app_backend
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/xeland314/reqs_app_lib.git

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  uuid: ^3.0.4
  decimal: ^3.0.2
  rational: ^2.2.3
  csv: ^6.0.0
  excel: ^4.0.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
